// Copyright 2020 The Sqlite Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package crt2 // import "modernc.org/sqlite/internal/crt2"

var CAPI = map[string]struct{}{
	"ferror": {},
	"fstat":  {},
	// 	"ftruncate":             {},
	// 	"lstat":                 {},
	"pthread_cond_destroy":  {},
	"pthread_cond_init":     {},
	"pthread_cond_signal":   {},
	"pthread_cond_wait":     {},
	"pthread_create":        {},
	"pthread_detach":        {},
	"pthread_mutex_destroy": {},
	"pthread_mutex_init":    {},
	"pthread_mutex_lock":    {},
	"pthread_mutex_unlock":  {},
	// 	"readdir":               {},
	// 	"rename":                {},
	"sched_yield": {},
	// 	"stat":                  {},
	//
	// 	"__assert_fail":         {},
	// 	"__builtin_exit":        {},
	// 	"__builtin_trap":        {},
	// 	"__builtin_unreachable": {},
	// 	"abort":                 {},
	// 	"calloc":                {},
	// 	"exit":                  {},
	// 	"free":                  {},
	// 	"malloc":                {},
	// 	"realloc":               {},
	//
	// 	"TclFreeObj":                 {},
	// 	"Tcl_Alloc":                  {},
	// 	"Tcl_AppendElement":          {},
	// 	"Tcl_AppendObjToObj":         {},
	// 	"Tcl_AppendResult":           {},
	// 	"Tcl_AppendStringsToObj":     {},
	// 	"Tcl_AttemptAlloc":           {},
	// 	"Tcl_AttemptRealloc":         {},
	// 	"Tcl_BackgroundError":        {},
	// 	"Tcl_CreateChannel":          {},
	// 	"Tcl_CreateCommand":          {},
	// 	"Tcl_CreateInterp":           {},
	// 	"Tcl_CreateObjCommand":       {},
	// 	"Tcl_CreateThread":           {},
	// 	"Tcl_DStringAppend":          {},
	// 	"Tcl_DStringAppendElement":   {},
	// 	"Tcl_DStringFree":            {},
	// 	"Tcl_DStringInit":            {},
	// 	"Tcl_DeleteCommand":          {},
	// 	"Tcl_DeleteHashTable":        {},
	// 	"Tcl_DeleteInterp":           {},
	// 	"Tcl_DoOneEvent":             {},
	// 	"Tcl_DuplicateObj":           {},
	// 	"Tcl_Eval":                   {},
	// 	"Tcl_EvalEx":                 {},
	// 	"Tcl_EvalObjEx":              {},
	// 	"Tcl_ExitThread":             {},
	// 	"Tcl_FindExecutable":         {},
	// 	"Tcl_FirstHashEntry":         {},
	// 	"Tcl_Flush":                  {},
	// 	"Tcl_Free":                   {},
	// 	"Tcl_GetBoolean":             {},
	// 	"Tcl_GetBooleanFromObj":      {},
	// 	"Tcl_GetByteArrayFromObj":    {},
	// 	"Tcl_GetChannel":             {},
	// 	"Tcl_GetChannelInstanceData": {},
	// 	"Tcl_GetChannelName":         {},
	// 	"Tcl_GetCharLength":          {},
	// 	"Tcl_GetCommandInfo":         {},
	// 	"Tcl_GetCurrentThread":       {},
	// 	"Tcl_GetDouble":              {},
	// 	"Tcl_GetDoubleFromObj":       {},
	// 	"Tcl_GetIndexFromObjStruct":  {},
	// 	"Tcl_GetInt":                 {},
	// 	"Tcl_GetIntFromObj":          {},
	// 	"Tcl_GetObjResult":           {},
	// 	"Tcl_GetSlave":               {},
	// 	"Tcl_GetString":              {},
	// 	"Tcl_GetStringFromObj":       {},
	// 	"Tcl_GetStringResult":        {},
	// 	"Tcl_GetTime":                {},
	// 	"Tcl_GetVar2":                {},
	// 	"Tcl_GetVar2Ex":              {},
	// 	"Tcl_GetVersion":             {},
	// 	"Tcl_GetWideIntFromObj":      {},
	// 	"Tcl_GlobalEval":             {},
	// 	"Tcl_InitHashTable":          {},
	// 	"Tcl_LinkVar":                {},
	// 	"Tcl_ListObjAppendElement":   {},
	// 	"Tcl_ListObjGetElements":     {},
	// 	"Tcl_ListObjIndex":           {},
	// 	"Tcl_ListObjLength":          {},
	// 	"Tcl_NRAddCallback":          {},
	// 	"Tcl_NRCallObjProc":          {},
	// 	"Tcl_NRCreateCommand":        {},
	// 	"Tcl_NREvalObj":              {},
	// 	"Tcl_NewByteArrayObj":        {},
	// 	"Tcl_NewDoubleObj":           {},
	// 	"Tcl_NewIntObj":              {},
	// 	"Tcl_NewListObj":             {},
	// 	"Tcl_NewObj":                 {},
	// 	"Tcl_NewStringObj":           {},
	// 	"Tcl_NewWideIntObj":          {},
	// 	"Tcl_NextHashEntry":          {},
	// 	"Tcl_ObjGetVar2":             {},
	// 	"Tcl_ObjSetVar2":             {},
	// 	"Tcl_Panic":                  {},
	// 	"Tcl_PkgProvideEx":           {},
	// 	"Tcl_RegisterChannel":        {},
	// 	"Tcl_ResetResult":            {},
	// 	"Tcl_Seek":                   {},
	// 	"Tcl_SetCommandInfo":         {},
	// 	"Tcl_SetIntObj":              {},
	// 	"Tcl_SetObjResult":           {},
	// 	"Tcl_SetResult":              {},
	// 	"Tcl_SetSystemEncoding":      {},
	// 	"Tcl_SetVar2":                {},
	// 	"Tcl_SetWideIntObj":          {},
	// 	"Tcl_ThreadAlert":            {},
	// 	"Tcl_ThreadQueueEvent":       {},
	// 	"Tcl_TranslateFileName":      {},
	// 	"Tcl_UnregisterChannel":      {},
	// 	"Tcl_UnsetVar2":              {},
	// 	"Tcl_UtfToLower":             {},
	// 	"Tcl_VarEval":                {},
	// 	"Tcl_WrongNumArgs":           {},
}
